### ISSUE TITLE
Import list of all cities/landkreise as dropdown

### ISSUE THREAD

**Issue by lislis** [feminizidmap/feminizidmap-backend#49]
@lislis ich hab jetzt die städte alle importiert in eine collection `[Dropdown] City` (müsste man für den View noch umbenennen). Die besteht aus

* name
* postal code
* county
* federal state

#### TODO
_note 2 myself_

- [ ] Lifecycle hook für die Address component. `onCreate` muss via Kombination aus Stadt-Name und PLZ das richtige Item aus der Collection gefetched und die anderen Felder entsprechend befüllt werden. Easy
- [ ] Die auto-assigneden Felder müssen disabled werden. Das geht nur über fine-grained role permissions (leider)
- [ ] Migration der Altdaten auf das neue Schema

@lislis damit entfällt doch dann eigentlich die Verwendung für das GoogleMaps Plugin, das eh broken ist oder? Bzw generelle Frage: Reicht euch als räumliche Auflösung die Stadt oder sollte es schon noch genauer sein? Also bis auf Adresse runter?

#### Specification  Lifecycle Hook
* `onCreate` und `onUpdate` in address component
* mapping / matching der richtigen Elemente soll - sofern nicht editiert - diese attr matchen
  * Bundesland (`federal_state`)
  * county (`county`)
* Das matching geschieht via filter auf `api::dropdown-city.dropdown-city`, diese collection durchsuchen bis pair `name` + `postal_code` matchen und obige values entsprechend setzen

**Comment by lislis** [comment]
> damit entfällt doch dann eigentlich die Verwendung für das GoogleMaps Plugin, das eh broken ist oder? Bzw generelle Frage: Reicht euch als räumliche Auflösung die Stadt oder sollte es schon noch genauer sein? Also bis auf Adresse runter?

Das Geocoding wäre noch wichtig, aber das kann gern auf Stadt-Ebene sein

**Comment by andneuma** [comment]
Huhu, das seeding funktioniert so

![image](https://github.com/user-attachments/assets/d44dec60-2cc2-407c-beae-45e97f7a7393)

**Comment by lislis** [comment]
<img width="959" alt="Screenshot 2024-11-26 at 10 51 08" src="https://github.com/user-attachments/assets/32265ff3-3f67-4ed3-b4a8-72577f919b01">
@andneuma kannst du das csv mit einchecken?

**Comment by andneuma** [comment]
done
